version: "2.3"

services:
  php:
    image: wodby/drupal-php:7.2-4.7.5
    env_file: ./.env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME_JMOLIVAS: ${DATABASE_NAME_JMOLIVAS}
      DATABASE_USER_JMOLIVAS: ${DATABASE_USER_JMOLIVAS}
      DATABASE_PASSWORD_JMOLIVAS: ${DATABASE_PASSWORD_JMOLIVAS}
      DATABASE_HOST_JMOLIVAS: ${DATABASE_HOST_JMOLIVAS}
      DATABASE_NAME_ENZO: ${DATABASE_NAME_ENZO}
      DATABASE_USER_ENZO: ${DATABASE_USER_ENZO}
      DATABASE_PASSWORD_ENZO: ${DATABASE_PASSWORD_ENZO}
      DATABASE_HOST_ENZO: ${DATABASE_HOST_ENZO}
      DATABASE_NAME_OMERS: ${DATABASE_NAME_OMERS}
      DATABASE_USER_OMERS: ${DATABASE_USER_OMERS}
      DATABASE_PASSWORD_OMERS: ${DATABASE_PASSWORD_OMERS}
      DATABASE_HOST_OMERS: ${DATABASE_HOST_OMERS}
      
    volumes:
      - ./:${DRUPAL_ROOT}:delegated

  nginx:
    image: wodby/drupal-nginx:8-1.13-4.0.3
    env_file: ./.env
    restart: always
    networks:
      - web
      - default
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: ${SERVER_ROOT}
    volumes:
      - ./:${DRUPAL_ROOT}:delegated
    labels:
      - 'traefik.backend=nginx'
      - "traefik.docker.network=web"
      - 'traefik.enable=true'
      - 'traefik.jmolivas.port=80'
      - 'traefik.jmolivas.frontend.rule=Host:${URL_SITE_JMOLIVAS}'
      - "traefik.jmolivas.frontend.redirect.regex=^https?://www.${URL_SITE_JMOLIVAS}/(.*)"
      - "traefik.jmolivas.frontend.redirect.replacement=https://${URL_SITE_JMOLIVAS}/$${1}"
      - 'traefik.enzo.port=80'
      - 'traefik.enzo.frontend.rule=Host:${URL_SITE_ENZO}'
      - "traefik.enzo.frontend.redirect.regex=^https?://www.${URL_SITE_ENZO}/(.*)"
      - "traefik.enzo.frontend.redirect.replacement=https://${URL_SITE_ENZO}/$${1}"
      - 'traefik.omers.port=80'
      - 'traefik.omers.frontend.rule=Host:${URL_SITE_OMERS}'
      - "traefik.omers.frontend.redirect.regex=^https?://www.${URL_SITE_OMERS}/(.*)"
      - "traefik.omers.frontend.redirect.replacement=https://${URL_SITE_OMERS}/$${1}"

  traefik:
    image: traefik:1.6-alpine
    restart: always
    networks:
      - web
      - default
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik/traefik.toml:/etc/traefik/traefik.toml
      - ../traefik/acme.json:/etc/traefik/acme.json

networks:
  web:
    external: true