version: "2.3"

services:
  mariadb_jmolivas:
    image: wodby/mariadb:10.2-3.1.3
    env_file: ./.env
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: ${DATABASE_NAME_JMOLIVAS}
      MYSQL_USER: ${DATABASE_USER_JMOLIVAS}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD_JMOLIVAS}
    volumes:
      - mariadb_jmolivas:/var/lib/mysql
      # Place init .sql file(s) here
      - ./mariadb-init-jmolivas:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mariadb_enzo:
    image: wodby/mariadb:10.2-3.1.3
    env_file: ./.env
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: ${DATABASE_NAME_ENZO}
      MYSQL_USER: ${DATABASE_NAME_ENZO}
      MYSQL_PASSWORD: ${DATABASE_NAME_ENZO}
    volumes:
      - mariadb_enzo:/var/lib/mysql
      # Place init .sql file(s) here
      - ./mariadb-init-enzo:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php:
    image: wodby/drupal-php:7.2-4.7.5
    env_file: ./.env
    restart: always
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME_JMOLIVAS: ${DATABASE_NAME_JMOLIVAS}
      DATABASE_USER_JMOLIVAS: ${DATABASE_USER_JMOLIVAS}
      DATABASE_PASSWORD_JMOLIVAS: ${DATABASE_PASSWORD_JMOLIVAS}
      DATABASE_HOST_JMOLIVAS: ${DATABASE_HOST_JMOLIVAS}
      DATABASE_NAME_ENZO: ${DATABASE_NAME_ENZO}
      DATABASE_USER_ENZO: ${DATABASE_USER_ENZO}
      DATABASE_PASSWORD_ENZO: ${DATABASE_PASSWORD_ENZO}
      DATABASE_HOST_ENZO: ${DATABASE_HOST_ENZO}
      
    volumes:
      - ./:${DRUPAL_ROOT}:delegated
    depends_on:
      mariadb_jmolivas:
        condition: service_healthy
      mariadb_enzo:
        condition: service_healthy

  nginx:
    image: wodby/drupal-nginx:8-1.13-4.0.3
    env_file: ./.env
    restart: always
    networks:
      - web
      - default
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: ${SERVER_ROOT}
    volumes:
      - ./:${DRUPAL_ROOT}:delegated
    labels:
      - 'traefik.backend=nginx'
      - "traefik.docker.network=web"
      - 'traefik.enable=true'
      - 'traefik.jmolivas.port=80'
      - 'traefik.jmolivas.frontend.rule=Host:${URL_SITE_JMOLIVAS}'
      - "traefik.jmolivas.frontend.redirect.regex=^https?://www.${URL_SITE_JMOLIVAS}/(.*)"
      - "traefik.jmolivas.frontend.redirect.replacement=https://${URL_SITE_JMOLIVAS}/$${1}"
      - 'traefik.enzo.port=80'
      - 'traefik.enzo.frontend.rule=Host:${URL_SITE_ENZO}'
      - "traefik.enzo.frontend.redirect.regex=^https?://www.${URL_SITE_ENZO}/(.*)"
      - "traefik.enzo.frontend.redirect.replacement=https://${URL_SITE_ENZO}/$${1}"

  traefik:
    image: traefik:1.6-alpine
    restart: always
    networks:
      - web
      - default
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik/traefik.toml:/etc/traefik/traefik.toml
      - ../traefik/acme.json:/etc/traefik/acme.json

volumes:
  mariadb_enzo:
    driver: "local"
  mariadb_jmolivas:
    driver: "local"

networks:
  web:
    external: true